# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/spotify.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/spotify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/spotify.proto\x12\x0cspotify_grpc\"\x1f\n\x0f\x41uthCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"6\n\x0c\x41uthResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"9\n\x12LikedTracksRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\r\n\x05total\x18\x02 \x01(\x05\"b\n\x05Track\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\"\n\x05\x61lbum\x18\x03 \x01(\x0b\x32\x13.spotify_grpc.Album\x12\n\n\x02id\x18\x04 \x01(\t\x12\x0b\n\x03uri\x18\x05 \x01(\t\"K\n\x13LikedTracksResponse\x12#\n\x06tracks\x18\x01 \x03(\x0b\x32\x13.spotify_grpc.Track\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x1a\n\x0b\x41lbumImages\x12\x0b\n\x03url\x18\x01 \x03(\t\"Y\n\x05\x41lbum\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12)\n\x06images\x18\x04 \x01(\x0b\x32\x19.spotify_grpc.AlbumImages\"U\n\x14PlayNextTrackRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x19\n\x11\x63urrent_track_uri\x18\x02 \x01(\t\x12\x0c\n\x04uris\x18\x03 \x03(\t\"(\n\x15PlayNextTrackResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8f\x02\n\x0bSpotifyAuth\x12K\n\x0c\x45xchangeCode\x12\x1d.spotify_grpc.AuthCodeRequest\x1a\x1a.spotify_grpc.AuthResponse\"\x00\x12W\n\x0eGetLikedTracks\x12 .spotify_grpc.LikedTracksRequest\x1a!.spotify_grpc.LikedTracksResponse\"\x00\x12Z\n\rPlayNextTrack\x12\".spotify_grpc.PlayNextTrackRequest\x1a#.spotify_grpc.PlayNextTrackResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.spotify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHCODEREQUEST']._serialized_start=38
  _globals['_AUTHCODEREQUEST']._serialized_end=69
  _globals['_AUTHRESPONSE']._serialized_start=71
  _globals['_AUTHRESPONSE']._serialized_end=125
  _globals['_LIKEDTRACKSREQUEST']._serialized_start=127
  _globals['_LIKEDTRACKSREQUEST']._serialized_end=184
  _globals['_TRACK']._serialized_start=186
  _globals['_TRACK']._serialized_end=284
  _globals['_LIKEDTRACKSRESPONSE']._serialized_start=286
  _globals['_LIKEDTRACKSRESPONSE']._serialized_end=361
  _globals['_ALBUMIMAGES']._serialized_start=363
  _globals['_ALBUMIMAGES']._serialized_end=389
  _globals['_ALBUM']._serialized_start=391
  _globals['_ALBUM']._serialized_end=480
  _globals['_PLAYNEXTTRACKREQUEST']._serialized_start=482
  _globals['_PLAYNEXTTRACKREQUEST']._serialized_end=567
  _globals['_PLAYNEXTTRACKRESPONSE']._serialized_start=569
  _globals['_PLAYNEXTTRACKRESPONSE']._serialized_end=609
  _globals['_SPOTIFYAUTH']._serialized_start=612
  _globals['_SPOTIFYAUTH']._serialized_end=883
# @@protoc_insertion_point(module_scope)
