# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import spotify_pb2 as protos_dot_spotify__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/spotify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpotifyAuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeCode = channel.unary_unary(
                '/spotify_grpc.SpotifyAuth/ExchangeCode',
                request_serializer=protos_dot_spotify__pb2.AuthCodeRequest.SerializeToString,
                response_deserializer=protos_dot_spotify__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetLikedTracks = channel.unary_unary(
                '/spotify_grpc.SpotifyAuth/GetLikedTracks',
                request_serializer=protos_dot_spotify__pb2.LikedTracksRequest.SerializeToString,
                response_deserializer=protos_dot_spotify__pb2.LikedTracksResponse.FromString,
                _registered_method=True)
        self.PlayNextTrack = channel.unary_unary(
                '/spotify_grpc.SpotifyAuth/PlayNextTrack',
                request_serializer=protos_dot_spotify__pb2.PlayNextTrackRequest.SerializeToString,
                response_deserializer=protos_dot_spotify__pb2.PlayNextTrackResponse.FromString,
                _registered_method=True)
        self.GetAudioVisualData = channel.unary_unary(
                '/spotify_grpc.SpotifyAuth/GetAudioVisualData',
                request_serializer=protos_dot_spotify__pb2.GetAudioVisualDataRequest.SerializeToString,
                response_deserializer=protos_dot_spotify__pb2.GetAudioVisualDataResponse.FromString,
                _registered_method=True)


class SpotifyAuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExchangeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLikedTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayNextTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudioVisualData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpotifyAuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeCode,
                    request_deserializer=protos_dot_spotify__pb2.AuthCodeRequest.FromString,
                    response_serializer=protos_dot_spotify__pb2.AuthResponse.SerializeToString,
            ),
            'GetLikedTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikedTracks,
                    request_deserializer=protos_dot_spotify__pb2.LikedTracksRequest.FromString,
                    response_serializer=protos_dot_spotify__pb2.LikedTracksResponse.SerializeToString,
            ),
            'PlayNextTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayNextTrack,
                    request_deserializer=protos_dot_spotify__pb2.PlayNextTrackRequest.FromString,
                    response_serializer=protos_dot_spotify__pb2.PlayNextTrackResponse.SerializeToString,
            ),
            'GetAudioVisualData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudioVisualData,
                    request_deserializer=protos_dot_spotify__pb2.GetAudioVisualDataRequest.FromString,
                    response_serializer=protos_dot_spotify__pb2.GetAudioVisualDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spotify_grpc.SpotifyAuth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spotify_grpc.SpotifyAuth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpotifyAuth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExchangeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotify_grpc.SpotifyAuth/ExchangeCode',
            protos_dot_spotify__pb2.AuthCodeRequest.SerializeToString,
            protos_dot_spotify__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLikedTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotify_grpc.SpotifyAuth/GetLikedTracks',
            protos_dot_spotify__pb2.LikedTracksRequest.SerializeToString,
            protos_dot_spotify__pb2.LikedTracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayNextTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotify_grpc.SpotifyAuth/PlayNextTrack',
            protos_dot_spotify__pb2.PlayNextTrackRequest.SerializeToString,
            protos_dot_spotify__pb2.PlayNextTrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudioVisualData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spotify_grpc.SpotifyAuth/GetAudioVisualData',
            protos_dot_spotify__pb2.GetAudioVisualDataRequest.SerializeToString,
            protos_dot_spotify__pb2.GetAudioVisualDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
